export const PASSWORD_FORMAT="The length of the password must be between 8 and 30. Password must contain at least one uppercase letter, one lowercase letter, one number and one special character"
export const EMAIL_FORMAT="Email Should be Correct"
export const NO_PASSWORD="Fill Appropriate Password"
export const WRONG_PASSWORD="Wrong Password Format"
export const NO_PASSWORD_MATCH="New password and Confirm password not match"
export const CODE_VALIDATION="Code Should be of 6 Digit"